`timescale 1ns/1ps
`default_nettype none

module i2c_asep_top
  import asa_asep_pkg::*;
  import asa_i2c_asep_pkg::*;
(
  input  logic                                   clk,
  input  logic                                   rst,
  input  logic                                   soft_reset_i,
  input  logic                                   startup_sync_i,
  input  logic                                   cfg_reg_write_i,

  input  logic                                   root_tx_build_byte_i,
  input  logic                                   root_tx_build_bulk_write_i,
  input  logic                                   root_tx_build_bulk_read_i,
  input  logic                                   root_tx_build_cfg_write_i,
  input  logic                                   root_tx_build_cfg_read_i,
  input  asep_ts_mode_e                          root_ts_mode_i,
  input  logic [31:0]                            root_ts_value_i,
  input  logic                                   root_i2c_error_i,
  input  logic                                   root_byte_start_i,
  input  logic                                   root_byte_stop_i,
  input  logic                                   root_byte_ack_i,
  input  logic                                   root_byte_nack_i,
  input  logic                                   root_byte_data_valid_i,
  input  logic [7:0]                             root_byte_data_i,
  input  logic                                   root_bulk_current_loc_i,
  input  logic                                   root_bulk_offset_16b_i,
  input  logic [6:0]                             root_bulk_slave_addr_i,
  input  logic [15:0]                            root_bulk_offset_addr_i,
  input  logic [15:0]                            root_bulk_len_i,
  input  asep_packet_t                           root_bulk_wdata_i,
  input  logic [5:0]                             root_cfg_clock_rate_i,
  input  logic [3:0]                             root_cfg_addr_count_i,
  input  i2c_addr_cfg_vec_t                      root_cfg_addr_cfg_i,
  input  logic [15:0]                            watchdog_cycles_i,
  input  logic                                   root_rx_packet_valid_i,
  input  asep_packet_t                           root_rx_packet_i,
  input  logic [11:0]                            root_rx_packet_len_i,
  output logic                                   root_tx_packet_valid_o,
  output asep_packet_t                           root_tx_packet_o,
  output logic [11:0]                            root_tx_packet_len_o,
  output logic [7:0]                             root_tx_cmd_id_o,
  output logic                                   root_pending_o,
  output logic                                   root_timeout_o,
  output logic                                   root_resp_bulk_ack_seen_o,
  output logic                                   root_resp_bulk_read_seen_o,
  output logic                                   root_resp_cfg_ack_seen_o,
  output logic                                   root_resp_cfg_read_seen_o,
  output logic [7:0]                             root_resp_cmd_id_o,
  output logic                                   root_resp_ack_ok_o,
  output logic [15:0]                            root_resp_length_o,
  output logic [(ASEP_MAX_PACKET_BYTES*8)-1:0]   root_resp_ack_payload_o,
  output asep_packet_t                           root_resp_rdata_o,
  output logic [5:0]                             root_resp_cfg_clock_rate_o,
  output i2c_addr_cfg_vec_t                      root_resp_cfg_addr_cfg_o,
  output logic                                   root_resp_crc_error_o,
  output logic                                   root_resp_format_error_o,

  input  logic                                   asd_rx_packet_valid_i,
  input  asep_packet_t                           asd_rx_packet_i,
  input  logic [11:0]                            asd_rx_packet_len_i,
  input  logic                                   asd_resp_bulk_ack_valid_i,
  input  logic [15:0]                            asd_resp_bulk_ack_len_i,
  input  logic [(ASEP_MAX_PACKET_BYTES*8)-1:0]   asd_resp_bulk_ack_payload_i,
  input  logic                                   asd_resp_bulk_read_valid_i,
  input  logic [15:0]                            asd_resp_bulk_read_len_i,
  input  asep_packet_t                           asd_resp_bulk_rdata_i,
  input  logic                                   asd_resp_cfg_ack_valid_i,
  input  logic                                   asd_resp_cfg_ack_ok_i,
  input  logic                                   asd_resp_cfg_read_valid_i,
  input  logic [5:0]                             asd_resp_cfg_clock_rate_i,
  input  logic [3:0]                             asd_resp_cfg_addr_count_i,
  input  i2c_addr_cfg_vec_t                      asd_resp_cfg_addr_cfg_i,
  output logic                                   asd_tx_packet_valid_o,
  output asep_packet_t                           asd_tx_packet_o,
  output logic [11:0]                            asd_tx_packet_len_o,
  output logic                                   asd_req_byte_seen_o,
  output logic                                   asd_req_bulk_write_seen_o,
  output logic                                   asd_req_bulk_read_seen_o,
  output logic                                   asd_req_cfg_write_seen_o,
  output logic                                   asd_req_cfg_read_seen_o,
  output logic [7:0]                             asd_req_cmd_id_o,
  output logic                                   asd_req_i2c_error_o,
  output logic                                   asd_req_byte_start_o,
  output logic                                   asd_req_byte_stop_o,
  output logic                                   asd_req_byte_ack_o,
  output logic                                   asd_req_byte_nack_o,
  output logic                                   asd_req_byte_data_valid_o,
  output logic [7:0]                             asd_req_byte_data_o,
  output logic                                   asd_req_bulk_current_loc_o,
  output logic [6:0]                             asd_req_bulk_slave_addr_o,
  output logic [15:0]                            asd_req_bulk_offset_addr_o,
  output logic [15:0]                            asd_req_bulk_length_o,
  output asep_packet_t                           asd_req_bulk_wdata_o,
  output logic [5:0]                             asd_req_cfg_clock_rate_o,
  output logic [3:0]                             asd_req_cfg_addr_count_o,
  output i2c_addr_cfg_vec_t                      asd_req_cfg_addr_cfg_o,
  output logic                                   asd_req_crc_error_o,
  output logic                                   asd_req_format_error_o
);

  i2c_ase_tx u_root(
    .clk(clk), .rst(rst), .soft_reset_i(soft_reset_i), .startup_sync_i(startup_sync_i), .cfg_reg_write_i(cfg_reg_write_i),
    .tx_build_byte_i(root_tx_build_byte_i), .tx_build_bulk_write_i(root_tx_build_bulk_write_i), .tx_build_bulk_read_i(root_tx_build_bulk_read_i),
    .tx_build_cfg_write_i(root_tx_build_cfg_write_i), .tx_build_cfg_read_i(root_tx_build_cfg_read_i), .ts_mode_i(root_ts_mode_i), .ts_value_i(root_ts_value_i),
    .tx_i2c_error_i(root_i2c_error_i), .tx_byte_start_i(root_byte_start_i), .tx_byte_stop_i(root_byte_stop_i), .tx_byte_ack_i(root_byte_ack_i),
    .tx_byte_nack_i(root_byte_nack_i), .tx_byte_data_valid_i(root_byte_data_valid_i), .tx_byte_data_i(root_byte_data_i),
    .tx_bulk_current_loc_i(root_bulk_current_loc_i), .tx_bulk_offset_16b_i(root_bulk_offset_16b_i), .tx_bulk_slave_addr_i(root_bulk_slave_addr_i),
    .tx_bulk_offset_addr_i(root_bulk_offset_addr_i), .tx_bulk_len_i(root_bulk_len_i), .tx_bulk_wdata_i(root_bulk_wdata_i),
    .cfg_clock_rate_i(root_cfg_clock_rate_i), .cfg_addr_count_i(root_cfg_addr_count_i), .cfg_addr_cfg_i(root_cfg_addr_cfg_i),
    .watchdog_cycles_i(watchdog_cycles_i), .rx_packet_valid_i(root_rx_packet_valid_i), .rx_packet_i(root_rx_packet_i), .rx_packet_len_i(root_rx_packet_len_i),
    .tx_packet_valid_o(root_tx_packet_valid_o), .tx_packet_o(root_tx_packet_o), .tx_packet_len_o(root_tx_packet_len_o), .tx_cmd_id_o(root_tx_cmd_id_o),
    .pending_o(root_pending_o), .timeout_o(root_timeout_o), .resp_bulk_ack_seen_o(root_resp_bulk_ack_seen_o),
    .resp_bulk_read_seen_o(root_resp_bulk_read_seen_o), .resp_cfg_ack_seen_o(root_resp_cfg_ack_seen_o), .resp_cfg_read_seen_o(root_resp_cfg_read_seen_o),
    .resp_cmd_id_o(root_resp_cmd_id_o), .resp_ack_ok_o(root_resp_ack_ok_o), .resp_length_o(root_resp_length_o),
    .resp_ack_payload_o(root_resp_ack_payload_o), .resp_rdata_o(root_resp_rdata_o), .resp_cfg_clock_rate_o(root_resp_cfg_clock_rate_o),
    .resp_cfg_addr_cfg_o(root_resp_cfg_addr_cfg_o), .resp_crc_error_o(root_resp_crc_error_o), .resp_format_error_o(root_resp_format_error_o)
  );

  i2c_asd_rx u_asd(
    .clk(clk), .rst(rst), .soft_reset_i(soft_reset_i), .ts_mode_i(root_ts_mode_i), .ts_value_i(root_ts_value_i),
    .rx_packet_valid_i(asd_rx_packet_valid_i), .rx_packet_i(asd_rx_packet_i), .rx_packet_len_i(asd_rx_packet_len_i),
    .resp_bulk_ack_valid_i(asd_resp_bulk_ack_valid_i), .resp_bulk_ack_len_i(asd_resp_bulk_ack_len_i), .resp_bulk_ack_payload_i(asd_resp_bulk_ack_payload_i),
    .resp_bulk_read_valid_i(asd_resp_bulk_read_valid_i), .resp_bulk_read_len_i(asd_resp_bulk_read_len_i), .resp_bulk_rdata_i(asd_resp_bulk_rdata_i),
    .resp_cfg_ack_valid_i(asd_resp_cfg_ack_valid_i), .resp_cfg_ack_ok_i(asd_resp_cfg_ack_ok_i), .resp_cfg_read_valid_i(asd_resp_cfg_read_valid_i),
    .resp_cfg_clock_rate_i(asd_resp_cfg_clock_rate_i), .resp_cfg_addr_count_i(asd_resp_cfg_addr_count_i), .resp_cfg_addr_cfg_i(asd_resp_cfg_addr_cfg_i),
    .tx_packet_valid_o(asd_tx_packet_valid_o), .tx_packet_o(asd_tx_packet_o), .tx_packet_len_o(asd_tx_packet_len_o),
    .req_byte_seen_o(asd_req_byte_seen_o), .req_bulk_write_seen_o(asd_req_bulk_write_seen_o), .req_bulk_read_seen_o(asd_req_bulk_read_seen_o),
    .req_cfg_write_seen_o(asd_req_cfg_write_seen_o), .req_cfg_read_seen_o(asd_req_cfg_read_seen_o), .req_cmd_id_o(asd_req_cmd_id_o),
    .req_i2c_error_o(asd_req_i2c_error_o), .req_byte_start_o(asd_req_byte_start_o), .req_byte_stop_o(asd_req_byte_stop_o),
    .req_byte_ack_o(asd_req_byte_ack_o), .req_byte_nack_o(asd_req_byte_nack_o), .req_byte_data_valid_o(asd_req_byte_data_valid_o),
    .req_byte_data_o(asd_req_byte_data_o), .req_bulk_current_loc_o(asd_req_bulk_current_loc_o), .req_bulk_slave_addr_o(asd_req_bulk_slave_addr_o),
    .req_bulk_offset_addr_o(asd_req_bulk_offset_addr_o), .req_bulk_length_o(asd_req_bulk_length_o), .req_bulk_wdata_o(asd_req_bulk_wdata_o),
    .req_cfg_clock_rate_o(asd_req_cfg_clock_rate_o), .req_cfg_addr_count_o(asd_req_cfg_addr_count_o), .req_cfg_addr_cfg_o(asd_req_cfg_addr_cfg_o),
    .req_crc_error_o(asd_req_crc_error_o), .req_format_error_o(asd_req_format_error_o)
  );

endmodule

`default_nettype wire
